baseURL = 'https://unleashingthepowerofstoicagile.com/'
languageCode = 'en-us'
title = 'Unleashing the Power of Stoic Agile'
theme = 'stoicagile'

[params]
  description = 'Integrating ancient Stoic wisdom with modern Agile practices to build resilient teams and better products.'
  author = 'John McFadyen'

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    name = 'About'
    url = '/#about'
    weight = 20
  [[menu.main]]
    name = 'Services'
    url = '/#services'
    weight = 30
  [[menu.main]]
    name = 'Blog'
    url = '/blog/'
    weight = 40
  [[menu.main]]
    name = 'Connect'
    url = '/#contact'
    weight = 50

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
